# Включен ли вайтлист
whitelist-enabled: true

# Сообщение при кике
kick-message: '&cВы не в списке разрешенных игроков!'

# Сообщение при входе
join-message: '&e{player} &aзалетел к нам!'

# Сообщение при входе администратора
admin-join-message: '&cАдминистратор сервера &6{player} &cзашел на сервер!'

# Список разрешенных игроков (никнеймы в нижнем регистре)
allowed-players:
  - il0veminecraft14
  - xd_kar
  - lagaha
  - clayworld200
  - frutikkek
  - sulayd27
  - unhappyparrot012
  - anonsn
  - marinaksolotl

# Список администраторов
admins:
  - il0veminecraft14
  - UnHappyParrot012